# Site Configuration
title: Farm Business Plan
description: A comprehensive farm business plan repository.
url: "https://justaghost.github.io/farm-business-plan/"
baseurl: "/farm-business-plan/"
theme: minima

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
collections:
  docs:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
