# Site Configuration
title: Farm Business Plan
description: A comprehensive farm business plan repository.
url: "https://justaghost.github.io/farm-business-plan/"
baseurl: "/farm-business-plan/"
theme: jekyll-theme-cayman

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Sass Configuration
sass:
  load_paths:
    - assets/css

# Navigation
collections:
  docs:
    output: true
    permalink: /:path/
  assets:
    output: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Version Info
version: "1.0.2"
