# Netlify Configuration for Farm Business Plan Application
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command for Next.js static export
  command = "npm run build"
  
  # Directory containing the static files after build
  publish = "out"
  
  # Node.js version to use
  [build.environment]
    NODE_VERSION = "18"

# Deploy Preview settings for pull requests
[context.deploy-preview]
  command = "npm run build"
  publish = "out"

# Branch deploy settings for non-production branches
[context.branch-deploy]
  command = "npm run build"
  publish = "out"

# Production-specific settings
[context.production]
  command = "npm run build"
  publish = "out"

# Redirect rules for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
