# Netlify Configuration for Farm Business Plan Application
# https://docs.netlify.com/configure-builds/file-based-configuration/
#
# This configuration deploys Next.js as a dynamic application with serverless functions
# and API routes support, rather than a static export.

[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Publish directory for Next.js (Netlify will handle .next directory automatically)
  publish = ".next"
  
  # Node.js version to use
  [build.environment]
    NODE_VERSION = "18"

# Deploy Preview settings for pull requests
[context.deploy-preview]
  command = "npm run build"

# Branch deploy settings for non-production branches
[context.branch-deploy]
  command = "npm run build"

# Production-specific settings
[context.production]
  command = "npm run build"

# Next.js plugin for Netlify - enables serverless functions and ISR
[[plugins]]
  package = "@netlify/plugin-nextjs"
