name: Deploy Marketing (Next.js)

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "components/**"
      - "types/**"
      - "package.json"
      - "package-lock.json"
      - "next.config.js"
      - "tsconfig.json"
      - "tailwind.config.ts"
      - "postcss.config.js"
      - ".eslintrc.json"
      - "netlify.toml"
      - ".github/workflows/netlify-deploy.yml"
  pull_request:
    paths:
      - "app/**"
      - "components/**"
      - "types/**"
      - "package.json"
      - "package-lock.json"
      - "next.config.js"
      - "tsconfig.json"
      - "tailwind.config.ts"
      - "postcss.config.js"
      - ".eslintrc.json"
      - "netlify.toml"
      - ".github/workflows/netlify-deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Skip format check for now - focus on deployment
      - name: Type Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Check Netlify secrets
        id: check_secrets
        run: |
          if [ -n "${{ secrets.NETLIFY_DEPLOY_TOKEN }}" ] && [ -n "${{ secrets.NETLIFY_SITE_ID }}" ]; then
            echo "secrets_available=true" >> $GITHUB_OUTPUT
          else
            echo "secrets_available=false" >> $GITHUB_OUTPUT
            echo "Warning: Netlify secrets not configured. Skipping deployment."
            echo "Missing secrets:"
            [ -z "${{ secrets.NETLIFY_DEPLOY_TOKEN }}" ] && echo "  - NETLIFY_DEPLOY_TOKEN"
            [ -z "${{ secrets.NETLIFY_SITE_ID }}" ] && echo "  - NETLIFY_SITE_ID"
          fi

      - name: Deploy to Netlify
        if: steps.check_secrets.outputs.secrets_available == 'true'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: "."
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Automated deploy"
          enable-commit-comment: false
          enable-commit-status: true
          alias: "prod"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  preview-deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Skip format check for now - focus on deployment
      - name: Type Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Check Netlify secrets (Preview)
        id: check_secrets_preview
        run: |
          if [ -n "${{ secrets.NETLIFY_DEPLOY_TOKEN }}" ] && [ -n "${{ secrets.NETLIFY_SITE_ID }}" ]; then
            echo "secrets_available=true" >> $GITHUB_OUTPUT
          else
            echo "secrets_available=false" >> $GITHUB_OUTPUT
            echo "Warning: Netlify secrets not configured. Skipping preview deployment."
            echo "Missing secrets:"
            [ -z "${{ secrets.NETLIFY_DEPLOY_TOKEN }}" ] && echo "  - NETLIFY_DEPLOY_TOKEN"
            [ -z "${{ secrets.NETLIFY_SITE_ID }}" ] && echo "  - NETLIFY_SITE_ID"
          fi

      - name: Sanitize branch name for Netlify alias
        id: sanitize_branch_name
        if: steps.check_secrets_preview.outputs.secrets_available == 'true'
        run: |
          # Sanitize branch name for Netlify alias (lowercase, replace / with -, remove invalid chars)
          SAFE_ALIAS=$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          echo "safe_alias=$SAFE_ALIAS" >> $GITHUB_OUTPUT
          echo "Original branch: ${{ github.head_ref }}"
          echo "Safe alias: $SAFE_ALIAS"

      - name: Deploy Preview to Netlify
        if: steps.check_secrets_preview.outputs.secrets_available == 'true'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: "."
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            "Deploy Preview from PR #${{
            github.event.pull_request.number }}"
          enable-commit-comment: true
          enable-commit-status: true
          alias: ${{ steps.sanitize_branch_name.outputs.safe_alias }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
