name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build and Deploy to Netlify
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            netlify deploy --dir=. --message="Deploy PR #${{ github.event.pull_request.number }}"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            netlify deploy --dir=. --prod --message="Production deploy from main"
          else
            netlify deploy --dir=. --message="Deploy from ${{ github.ref_name }}"
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-output
          path: .next/
          retention-days: 7
